# docker-compose file for a sinatra application with monogdb
# and sidekiq

version: "3.1"

services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        - environment=development
      dockerfile: ./devops/docker/Dockerfile
    environment:
      - APP_PORT=9393
      - RACK_ENV=development
      - MONGODB_HOST=mongodb
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb
    networks:
      - mongo

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - ./data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - workers

  # sidekiq:
  #   build:
  #     context: .
  #     args:
  #       - environment=development
  #     dockerfile: ./devops/docker/Dockerfile
  #   command: bundle exec sidekiq -r ./boot.rb  -C config/sidekiq.yml
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - mongodb
  #     - redis
  #   networks:
  #     - workers

networks:
  mongo:
  workers:
